language: java
jdk:
  - oraclejdk8

before_install:
  - chmod +x gradlew

before_deploy:
  - ./gradlew generatePomFileForMavenPublication

before_script:
  - chmod +x gradlew

script:
  - ./gradlew check
  - ./gradlew jacocoTestReport

deploy:
  provider: bintray
  file: "descriptor.json"
  user: $BINTRAY_API_USER
  key: $BINTRAY_API_KEY
  dry-run: false

after_success:
  - bash <(curl -s https://codecov.io/bash)